### ISSUE TITLE
Remove guava dependency

### ISSUE THREAD

**Issue by nils-christian** [everest-engineering/axon-crypto-shredding-extension#10]
Hi,

guava is a library which is often used in various projects and leads very often to version conflicts. In my experience libraries should almost never use guava - only applications should use it. You are currently using the library only for a single method - to find default values for fields that cannot be decrypted. I suggest to move the required code into your library and to remove guava as dependency.

**Comment by sluehr** [comment]
Ahh, yes. This one has been on my to-do list for a while :+1:

**Comment by sluehr** [comment]
The Guava dependency has been replaced with an extensible DefaultValueProvider.
