### ISSUE TITLE
Show the maven coordinates in the Readme file

### ISSUE THREAD

**Issue by nils-christian** [everest-engineering/axon-crypto-shredding-extension#4]
Hi,

Your extension is clearly deployed to maven central:

```
<dependency>
  <groupId>engineering.everest.axon</groupId>
  <artifactId>crypto-shredding-extension</artifactId>
  <version>...</version>
</dependency>
```

I think it would be helpful if those coordinates would be visible in the readme file which is shown on the first page of your Github project. Maybe even use a maven badge.

**Comment by sluehr** [comment]
G'day @nils-christian 

Apologies for leaving the issues you raised in limbo for nearly 2 years! This repository was not being actively monitored and notification emails weren't being received.

Thank you for taking the time to review this library and to provide feedback. It's very much appreciated!

I'm going to address some of the smaller issues that you have raised based on whether it helps with our current customer's project. Some, like this one, have been at the bottom of a long list of things we should get around to doing for way too long. 

Again, thank you and sorry for taking such a long time to get back to you.
