### ISSUE TITLE
DefaultAesEncrypterDecrypterFactory shouldn't be package visible

### ISSUE THREAD

**Issue by nils-christian** [everest-engineering/axon-crypto-shredding-extension#5]
Hi,

Currently the only implementation of the _EncrypterDecrypterFactory_ is the package-visible _DefaultAesEncrypterDecrypterFactory_. Without using the Spring _EncryptionAutoConfiguration_ (or without reflection), it is not possible to use the _DefaultAesEncrypterDecrypterFactory_. Therefore this class should have the _public_ modifier.

**Comment by sluehr** [comment]
I  have made the factory and the classes it instantiates public now to give library consumers more freedom.

Thanks for the suggestion!
