### ISSUE TITLE
EncryptionAutoConfiguration is not an auto configuration

### ISSUE THREAD

**Issue by nils-christian** [everest-engineering/axon-crypto-shredding-extension#6]
Hi,

In your library there is a _EncryptionAutoConfiguration_. However, this is not an auto configuration, as your jar file does not contain a _META-INF/spring.factories_ file. Such a file should contain something like
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=engineering.everest.axon.cryptoshredding.encryption.EncryptionAutoConfiguration
```
Maybe it would also be a good idea to provide a separate module for the Spring adapter. Otherwise you force the Spring libraries into the dependency tree.

**Comment by sluehr** [comment]
Thanks for the heads up - it might take a while for me to cycle back to this one.

(I promise it won't take another 2 years)
