### ISSUE TITLE
DefaultAesKeyGenerator  shouldn't be package visible

### ISSUE THREAD

**Issue by nils-christian** [everest-engineering/axon-crypto-shredding-extension#7]
Hi,

Currently the only implementation of the _KeyGenerator_ is the package-visible _DefaultAesKeyGenerator_. Without using the Spring EncryptionAutoConfiguration (or without reflection), it is not possible to use the _DefaultAesKeyGenerator_. Therefore this class should have the public modifier.

**Comment by sluehr** [comment]
Agreed - done as part of #5
