### ISSUE TITLE
Make the key extractor configurable

### ISSUE THREAD

**Issue by nils-christian** [everest-engineering/axon-crypto-shredding-extension#8]
Hi,

Currently, the _CryptoShreddingSerializer_ has a hardcoded logic for extracting the key (in the _convertToString_ method) and knows Strings, UUIDs, Longs, and Integers. However, we usually use specific classes for the ids. For instance, if we have an aggregate _Customer_, we would have a class _CustomerId_ which wraps an UUID. It would therefore be useful if we could configure the key extractor somehow. This would basically be a function from the key object to _String_.

**Comment by sluehr** [comment]
We've added an extensible converter for serialising key identifiers to strings.
