### ISSUE TITLE
Better abstraction for the SecretKeyRepository

### ISSUE THREAD

**Issue by nils-christian** [everest-engineering/axon-crypto-shredding-extension#9]
Hi,

Currently your library uses the _SecretKeyRepository_ which is basically a JPA repository. This forces the usage of JPA and a shared database between the micro services, which is not always desired. Maybe it would be a nice feature to use a simpler interface (with the methods `create`, `save`, `findById`). You could then provide a default implementation which uses JPA. Other implementations could, for instance, use queries and commands to access a shared key store.

**Comment by prasanna214** [comment]
Made `SecretKeyRepository` a common interface in version `2.0.0`. The default JPA implementation has been moved to [lhotse](https://github.com/everest-engineering/lhotse) now.
